/**
 * PlanPanel - UltraPlan viewer with analysis, outline, section detail
 *
 * Displays multi-phase plans generated by the LLM. Users can view
 * the analysis, review sections (with deps/risks/effort), approve/reject,
 * and execute approved plans.
 */
import { useCallback, useMemo, useRef, useEffect, useState } from 'react';
import { usePlanStore } from '@/stores/planStore';
import type { PlanPhase } from '@/stores/planStore';
import { useSessionStore } from '@/stores/sessionStore';
import Markdown from '@/components/common/Markdown';
import type { PlanSection } from '@/types';

// ==================== Status helpers ====================

const STATUS_CONFIG: Record<PlanSection['status'], { icon: string; label: string; cls: string }> = {
  pending:     { icon: '○', label: 'Pending',     cls: 'pending' },
  approved:    { icon: '✓', label: 'Approved',    cls: 'approved' },
  rejected:    { icon: '—', label: 'Skipped',     cls: 'rejected' },
  in_progress: { icon: '◎', label: 'Running',     cls: 'running' },
  completed:   { icon: '●', label: 'Completed',   cls: 'completed' },
  failed:      { icon: '✗', label: 'Failed',      cls: 'failed' },
};

const EFFORT_CONFIG: Record<string, { label: string; cls: string }> = {
  low:    { label: 'Low',    cls: 'effort-low' },
  medium: { label: 'Medium', cls: 'effort-medium' },
  high:   { label: 'High',   cls: 'effort-high' },
};

// ==================== Phase Indicator ====================

function PhaseIndicator({ phase }: { phase: PlanPhase }) {
  const analysisTool = usePlanStore((s) => s.analysisTool);
  if (!phase) return null;

  let label: string;
  if (phase === 'analysis' && analysisTool) {
    label = `Exploring: ${analysisTool.toolName} (${analysisTool.toolCount})`;
  } else if (phase === 'analysis') {
    label = 'Deep analysis...';
  } else {
    label = 'Structuring plan...';
  }

  return (
    <div className="plan-phase-indicator">
      <div className="plan-spinner small" />
      <span>{label}</span>
    </div>
  );
}

// ==================== Analysis Panel ====================

function AnalysisView({ analysis, onClose }: { analysis: string; onClose: () => void }) {
  return (
    <div className="plan-analysis-view">
      <div className="plan-analysis-header">
        <span className="plan-analysis-title">Deep Analysis</span>
        <button className="plan-header-btn" onClick={onClose} title="Close analysis">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>
      <div className="plan-analysis-body">
        <Markdown content={analysis} />
      </div>
    </div>
  );
}

// ==================== Plan Outline (left sidebar) ====================

function PlanOutline({
  sections,
  activeSection,
  onSelect,
}: {
  sections: PlanSection[];
  activeSection: string | null;
  onSelect: (id: string) => void;
}) {
  return (
    <div className="plan-outline">
      <div className="plan-outline-title">Sections</div>
      <div className="plan-outline-list">
        {sections.map((s, i) => {
          const cfg = STATUS_CONFIG[s.status];
          const effort = s.effort ? EFFORT_CONFIG[s.effort] : null;
          return (
            <div
              key={s.id}
              className={`plan-outline-item ${cfg.cls}${activeSection === s.id ? ' active' : ''}`}
              onClick={() => onSelect(s.id)}
            >
              <span className={`plan-outline-status ${cfg.cls}`}>{cfg.icon}</span>
              <span className="plan-outline-num">{i + 1}.</span>
              <span className="plan-outline-text">{s.title}</span>
              {effort && (
                <span className={`plan-outline-effort ${effort.cls}`}>{effort.label}</span>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ==================== Section Renderer ====================

function PlanSectionView({ section, allSections }: { section: PlanSection; allSections: PlanSection[] }) {
  const [feedbackText, setFeedbackText] = useState('');
  const [showFeedback, setShowFeedback] = useState(false);
  const approveSection = usePlanStore((s) => s.approveSection);
  const rejectSection = usePlanStore((s) => s.rejectSection);
  const skipSection = usePlanStore((s) => s.skipSection);
  const isExecuting = usePlanStore((s) => s.isExecuting);
  const isRegenerating = usePlanStore((s) => s.regeneratingSections.includes(section.id));

  const cfg = STATUS_CONFIG[section.status];
  const effort = section.effort ? EFFORT_CONFIG[section.effort] : null;
  const canAct = (section.status === 'pending' || section.status === 'rejected') && !isRegenerating;

  const handleReject = useCallback(() => {
    if (feedbackText.trim()) {
      rejectSection(section.id, feedbackText.trim());
      setFeedbackText('');
      setShowFeedback(false);
    }
  }, [section.id, feedbackText, rejectSection]);

  const depNames = (section.dependencies || []).map((depId) => {
    const dep = allSections.find((s) => s.id === depId);
    return dep ? dep.title : depId;
  });

  return (
    <div className="plan-section-view">
      <div className="plan-section-header">
        <span className={`plan-section-badge ${cfg.cls}`}>
          {isRegenerating ? 'Revising...' : cfg.label}
        </span>
        {effort && (
          <span className={`plan-section-effort ${effort.cls}`}>
            {effort.label} effort
          </span>
        )}
        <h3>{section.title}</h3>
      </div>

      {isRegenerating && (
        <div className="plan-section-regenerating">
          <div className="plan-spinner small" />
          <span>Regenerating section based on your feedback...</span>
        </div>
      )}

      <div className={`plan-section-body${isRegenerating ? ' dimmed' : ''}`}>
        <Markdown content={section.description} />

        {/* Dependencies */}
        {depNames.length > 0 && (
          <div className="plan-section-meta">
            <span className="plan-meta-label">Depends on:</span>
            <span className="plan-meta-value">{depNames.join(', ')}</span>
          </div>
        )}

        {/* Steps */}
        {section.steps.length > 0 && (
          <div className="plan-section-steps">
            <div className="plan-steps-title">Steps</div>
            <ol>
              {section.steps.map((step, i) => (
                <li key={i}>{step}</li>
              ))}
            </ol>
          </div>
        )}

        {/* Risks */}
        {section.risks && section.risks.length > 0 && (
          <div className="plan-section-risks">
            <div className="plan-risks-title">Risks</div>
            <ul>
              {section.risks.map((risk, i) => (
                <li key={i}>{risk}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Validation */}
        {section.validation && (
          <div className="plan-section-meta">
            <span className="plan-meta-label">Validation:</span>
            <span className="plan-meta-value">{section.validation}</span>
          </div>
        )}

        {/* Execution result */}
        {section.result && (
          <div className={`plan-section-result ${section.status === 'failed' ? 'error' : ''}`}>
            <Markdown content={section.result} />
          </div>
        )}
      </div>

      {canAct && !isExecuting && (
        <div className="plan-section-actions">
          <button className="plan-btn approve" onClick={() => approveSection(section.id)}>
            Approve
          </button>
          <button
            className="plan-btn reject"
            onClick={() => setShowFeedback(!showFeedback)}
          >
            Revise
          </button>
          <button
            className="plan-btn skip"
            onClick={() => skipSection(section.id)}
            title="Skip this section — it won't be executed"
          >
            Skip
          </button>
        </div>
      )}

      {showFeedback && canAct && (
        <div className="plan-feedback-box">
          <textarea
            value={feedbackText}
            onChange={(e) => setFeedbackText(e.target.value)}
            placeholder="Describe what to change..."
            rows={3}
            autoFocus
          />
          <div className="plan-feedback-actions">
            <button className="plan-btn submit" onClick={handleReject} disabled={!feedbackText.trim()}>
              Submit Feedback
            </button>
            <button className="plan-btn cancel" onClick={() => { setShowFeedback(false); setFeedbackText(''); }}>
              Cancel
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

// ==================== Main Panel ====================

export default function PlanPanel() {
  const currentPlan = usePlanStore((s) => s.currentPlan);
  const isGenerating = usePlanStore((s) => s.isGenerating);
  const isExecuting = usePlanStore((s) => s.isExecuting);
  const activeSection = usePlanStore((s) => s.activeSection);
  const error = usePlanStore((s) => s.error);
  const currentPhase = usePlanStore((s) => s.currentPhase);
  const showAnalysis = usePlanStore((s) => s.showAnalysis);
  const setActiveSection = usePlanStore((s) => s.setActiveSection);
  const setShowAnalysis = usePlanStore((s) => s.setShowAnalysis);
  const approveAll = usePlanStore((s) => s.approveAll);
  const executePlan = usePlanStore((s) => s.executePlan);
  const clearPlan = usePlanStore((s) => s.clearPlan);
  const clearError = usePlanStore((s) => s.clearError);
  const currentSessionId = useSessionStore((s) => s.currentSessionId);

  const panelRef = useRef<HTMLDivElement>(null);
  const resizeRef = useRef<HTMLDivElement>(null);

  // Resize handle
  useEffect(() => {
    const handle = resizeRef.current;
    const panel = panelRef.current;
    if (!handle || !panel) return;

    let dragging = false;
    let startX = 0;
    let startW = 0;

    const onDown = (e: MouseEvent) => {
      dragging = true;
      startX = e.clientX;
      startW = panel.offsetWidth;
      handle.classList.add('dragging');
      document.body.style.cursor = 'ew-resize';
      document.body.style.userSelect = 'none';
      e.preventDefault();
    };
    const onMove = (e: MouseEvent) => {
      if (!dragging) return;
      const diff = startX - e.clientX;
      const maxW = Math.floor(window.innerWidth * 0.65);
      panel.style.width = Math.min(maxW, Math.max(360, startW + diff)) + 'px';
    };
    const onUp = () => {
      if (dragging) {
        dragging = false;
        handle.classList.remove('dragging');
        document.body.style.cursor = '';
        document.body.style.userSelect = '';
      }
    };

    handle.addEventListener('mousedown', onDown);
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseup', onUp);
    return () => {
      handle.removeEventListener('mousedown', onDown);
      document.removeEventListener('mousemove', onMove);
      document.removeEventListener('mouseup', onUp);
    };
  }, [currentPlan]);

  // Single-pass derived stats. Without memoization the parent re-renders this
  // 6+ times per plan-store update for what's effectively pure computation.
  const stats = useMemo(() => {
    const sections = currentPlan?.sections || [];
    let approvedCount = 0;
    let completedCount = 0;
    let hasPending = false;
    let allDecided = true;
    let totalEffort = 0;
    for (const s of sections) {
      if (s.status === 'approved') approvedCount++;
      if (s.status === 'completed') completedCount++;
      if (s.status === 'pending') hasPending = true;
      if (s.status !== 'approved' && s.status !== 'rejected') allDecided = false;
      totalEffort += s.effort === 'high' ? 3 : s.effort === 'medium' ? 2 : 1;
    }
    const len = sections.length;
    return {
      sections,
      approvedCount,
      completedCount,
      hasPending,
      hasApproved: approvedCount > 0,
      allDecided: len > 0 && allDecided,
      progress: len > 0 ? Math.round((completedCount / len) * 100) : 0,
      totalEffort,
      effortLabel: totalEffort <= len ? 'Low' : totalEffort >= len * 2.5 ? 'High' : 'Medium',
    };
  }, [currentPlan]);

  if (!currentPlan && !isGenerating) return null;

  const { sections, hasApproved, hasPending, allDecided, approvedCount, completedCount, progress, totalEffort, effortLabel } = stats;
  const activeItem = sections.find((s) => s.id === activeSection) || sections[0];

  return (
    <div className="plan-panel" ref={panelRef}>
      <div className="plan-resize-handle" ref={resizeRef} />

      {/* Header */}
      <div className="plan-panel-header">
        <div className="plan-header-left">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2" />
            <rect x="9" y="3" width="6" height="4" rx="1" />
            <path d="M9 14l2 2 4-4" />
          </svg>
          <span className="plan-header-title">
            {isGenerating ? 'UltraPlan' : currentPlan?.title || 'Plan'}
          </span>
        </div>
        <div className="plan-header-actions">
          {currentPlan?.analysis && (
            <button
              className={`plan-header-btn${showAnalysis ? ' active' : ''}`}
              onClick={() => setShowAnalysis(!showAnalysis)}
              title="Toggle deep analysis"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="11" cy="11" r="8" />
                <line x1="21" y1="21" x2="16.65" y2="16.65" />
              </svg>
            </button>
          )}
          {isExecuting && (
            <span className="plan-progress">{progress}%</span>
          )}
          <button className="plan-header-btn" onClick={clearPlan} title="Close plan">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>
      </div>

      {/* Error banner */}
      {error && (
        <div className="plan-error-banner">
          <span>{error}</span>
          <button onClick={clearError}>dismiss</button>
        </div>
      )}

      {/* Loading state with phase indicator */}
      {isGenerating && (
        <div className="plan-loading">
          <div className="plan-spinner" />
          <div className="plan-loading-phases">
            <PhaseIndicator phase={currentPhase} />
            {!currentPhase && <p>Preparing ultraplan...</p>}
          </div>
        </div>
      )}

      {/* Analysis overlay */}
      {showAnalysis && currentPlan?.analysis && (
        <AnalysisView analysis={currentPlan.analysis} onClose={() => setShowAnalysis(false)} />
      )}

      {/* Plan content */}
      {currentPlan && !showAnalysis && (
        <div className="plan-body">
          {/* Summary + effort badge */}
          {currentPlan.summary && (
            <div className="plan-summary">
              <Markdown content={currentPlan.summary} />
              {sections.length > 0 && (
                <div className="plan-summary-meta">
                  <span className="plan-meta-badge">{sections.length} sections</span>
                  <span className={`plan-meta-badge ${effortLabel.toLowerCase()}`}>
                    {effortLabel} effort
                  </span>
                </div>
              )}
            </div>
          )}

          <div className="plan-content-area">
            <PlanOutline
              sections={sections}
              activeSection={activeSection}
              onSelect={setActiveSection}
            />
            <div className="plan-detail">
              {activeItem ? (
                <PlanSectionView section={activeItem} allSections={sections} />
              ) : (
                <div className="plan-empty">Select a section</div>
              )}
            </div>
          </div>

          {/* Footer actions */}
          <div className="plan-footer">
            {hasPending && !isExecuting && (
              <button className="plan-btn approve-all" onClick={approveAll}>
                Approve All
              </button>
            )}
            {hasApproved && !isExecuting && currentSessionId && allDecided && (
              <button
                className="plan-btn execute"
                onClick={() => executePlan(currentSessionId)}
              >
                Execute {approvedCount}/{sections.length} Sections
              </button>
            )}
            {hasApproved && !isExecuting && !allDecided && (
              <span className="plan-footer-hint">
                Review remaining sections to execute
              </span>
            )}
            {isExecuting && (
              <span className="plan-executing-label">
                Executing... {completedCount}/{approvedCount}
              </span>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
