/**
 * PlanPanel - Plan Mode viewer with outline + section detail
 *
 * Displays structured plans generated by the LLM. Users can review,
 * approve/reject individual sections, and execute approved plans.
 */
import { useCallback, useRef, useEffect, useState } from 'react';
import { usePlanStore } from '@/stores/planStore';
import { useSessionStore } from '@/stores/sessionStore';
import Markdown from '@/components/common/Markdown';
import type { PlanSection } from '@/types';

// ==================== Status helpers ====================

const STATUS_CONFIG: Record<PlanSection['status'], { icon: string; label: string; cls: string }> = {
  pending:     { icon: '○', label: 'Pending',     cls: 'pending' },
  approved:    { icon: '✓', label: 'Approved',    cls: 'approved' },
  rejected:    { icon: '✗', label: 'Rejected',    cls: 'rejected' },
  in_progress: { icon: '◎', label: 'Running',     cls: 'running' },
  completed:   { icon: '●', label: 'Completed',   cls: 'completed' },
  failed:      { icon: '✗', label: 'Failed',      cls: 'failed' },
};

// ==================== Plan Outline (left sidebar) ====================

function PlanOutline({
  sections,
  activeSection,
  onSelect,
}: {
  sections: PlanSection[];
  activeSection: string | null;
  onSelect: (id: string) => void;
}) {
  return (
    <div className="plan-outline">
      <div className="plan-outline-title">Sections</div>
      <div className="plan-outline-list">
        {sections.map((s, i) => {
          const cfg = STATUS_CONFIG[s.status];
          return (
            <div
              key={s.id}
              className={`plan-outline-item ${cfg.cls}${activeSection === s.id ? ' active' : ''}`}
              onClick={() => onSelect(s.id)}
            >
              <span className={`plan-outline-status ${cfg.cls}`}>{cfg.icon}</span>
              <span className="plan-outline-num">{i + 1}.</span>
              <span className="plan-outline-text">{s.title}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ==================== Section Renderer ====================

function PlanSectionView({ section }: { section: PlanSection }) {
  const [feedbackText, setFeedbackText] = useState('');
  const [showFeedback, setShowFeedback] = useState(false);
  const approveSection = usePlanStore((s) => s.approveSection);
  const rejectSection = usePlanStore((s) => s.rejectSection);
  const isExecuting = usePlanStore((s) => s.isExecuting);

  const cfg = STATUS_CONFIG[section.status];
  const canAct = section.status === 'pending' || section.status === 'rejected';

  const handleReject = useCallback(() => {
    if (feedbackText.trim()) {
      rejectSection(section.id, feedbackText.trim());
      setFeedbackText('');
      setShowFeedback(false);
    }
  }, [section.id, feedbackText, rejectSection]);

  return (
    <div className="plan-section-view">
      <div className="plan-section-header">
        <span className={`plan-section-badge ${cfg.cls}`}>{cfg.label}</span>
        <h3>{section.title}</h3>
      </div>

      <div className="plan-section-body">
        <Markdown content={section.description} />

        {section.steps.length > 0 && (
          <div className="plan-section-steps">
            <div className="plan-steps-title">Steps</div>
            <ol>
              {section.steps.map((step, i) => (
                <li key={i}>{step}</li>
              ))}
            </ol>
          </div>
        )}

        {section.result && (
          <div className={`plan-section-result ${section.status === 'failed' ? 'error' : ''}`}>
            {section.result}
          </div>
        )}
      </div>

      {canAct && !isExecuting && (
        <div className="plan-section-actions">
          <button className="plan-btn approve" onClick={() => approveSection(section.id)}>
            Approve
          </button>
          <button
            className="plan-btn reject"
            onClick={() => setShowFeedback(!showFeedback)}
          >
            Revise
          </button>
        </div>
      )}

      {showFeedback && canAct && (
        <div className="plan-feedback-box">
          <textarea
            value={feedbackText}
            onChange={(e) => setFeedbackText(e.target.value)}
            placeholder="Describe what to change..."
            rows={3}
            autoFocus
          />
          <div className="plan-feedback-actions">
            <button className="plan-btn submit" onClick={handleReject} disabled={!feedbackText.trim()}>
              Submit Feedback
            </button>
            <button className="plan-btn cancel" onClick={() => { setShowFeedback(false); setFeedbackText(''); }}>
              Cancel
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

// ==================== Main Panel ====================

export default function PlanPanel() {
  const currentPlan = usePlanStore((s) => s.currentPlan);
  const isGenerating = usePlanStore((s) => s.isGenerating);
  const isExecuting = usePlanStore((s) => s.isExecuting);
  const activeSection = usePlanStore((s) => s.activeSection);
  const error = usePlanStore((s) => s.error);
  const setActiveSection = usePlanStore((s) => s.setActiveSection);
  const approveAll = usePlanStore((s) => s.approveAll);
  const executePlan = usePlanStore((s) => s.executePlan);
  const clearPlan = usePlanStore((s) => s.clearPlan);
  const clearError = usePlanStore((s) => s.clearError);
  const currentSessionId = useSessionStore((s) => s.currentSessionId);

  const panelRef = useRef<HTMLDivElement>(null);
  const resizeRef = useRef<HTMLDivElement>(null);

  // Resize handle
  useEffect(() => {
    const handle = resizeRef.current;
    const panel = panelRef.current;
    if (!handle || !panel) return;

    let dragging = false;
    let startX = 0;
    let startW = 0;

    const onDown = (e: MouseEvent) => {
      dragging = true;
      startX = e.clientX;
      startW = panel.offsetWidth;
      handle.classList.add('dragging');
      document.body.style.cursor = 'ew-resize';
      document.body.style.userSelect = 'none';
      e.preventDefault();
    };
    const onMove = (e: MouseEvent) => {
      if (!dragging) return;
      const diff = startX - e.clientX;
      const maxW = Math.floor(window.innerWidth * 0.65);
      panel.style.width = Math.min(maxW, Math.max(360, startW + diff)) + 'px';
    };
    const onUp = () => {
      if (dragging) {
        dragging = false;
        handle.classList.remove('dragging');
        document.body.style.cursor = '';
        document.body.style.userSelect = '';
      }
    };

    handle.addEventListener('mousedown', onDown);
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseup', onUp);
    return () => {
      handle.removeEventListener('mousedown', onDown);
      document.removeEventListener('mousemove', onMove);
      document.removeEventListener('mouseup', onUp);
    };
  }, [currentPlan]);

  // Not visible when no plan and not generating
  if (!currentPlan && !isGenerating) return null;

  const sections = currentPlan?.sections || [];
  const activeItem = sections.find((s) => s.id === activeSection) || sections[0];
  const allApproved = sections.length > 0 && sections.every((s) => s.status === 'approved');
  const hasPending = sections.some((s) => s.status === 'pending');
  const completedCount = sections.filter((s) => s.status === 'completed').length;
  const progress = sections.length > 0 ? Math.round((completedCount / sections.length) * 100) : 0;

  return (
    <div className="plan-panel" ref={panelRef}>
      <div className="plan-resize-handle" ref={resizeRef} />

      {/* Header */}
      <div className="plan-panel-header">
        <div className="plan-header-left">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2" />
            <rect x="9" y="3" width="6" height="4" rx="1" />
            <path d="M9 14l2 2 4-4" />
          </svg>
          <span className="plan-header-title">
            {isGenerating ? 'Generating Plan...' : currentPlan?.title || 'Plan'}
          </span>
        </div>
        <div className="plan-header-actions">
          {isExecuting && (
            <span className="plan-progress">{progress}%</span>
          )}
          <button className="plan-header-btn" onClick={clearPlan} title="Close plan">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>
      </div>

      {/* Error banner */}
      {error && (
        <div className="plan-error-banner">
          <span>{error}</span>
          <button onClick={clearError}>dismiss</button>
        </div>
      )}

      {/* Loading state */}
      {isGenerating && (
        <div className="plan-loading">
          <div className="plan-spinner" />
          <p>Analyzing task and generating plan...</p>
        </div>
      )}

      {/* Plan content */}
      {currentPlan && (
        <div className="plan-body">
          {/* Summary */}
          {currentPlan.summary && (
            <div className="plan-summary">
              <Markdown content={currentPlan.summary} />
            </div>
          )}

          <div className="plan-content-area">
            {/* Outline sidebar */}
            <PlanOutline
              sections={sections}
              activeSection={activeSection}
              onSelect={setActiveSection}
            />

            {/* Active section detail */}
            <div className="plan-detail">
              {activeItem ? (
                <PlanSectionView section={activeItem} />
              ) : (
                <div className="plan-empty">Select a section</div>
              )}
            </div>
          </div>

          {/* Footer actions */}
          <div className="plan-footer">
            {hasPending && !isExecuting && (
              <button className="plan-btn approve-all" onClick={approveAll}>
                Approve All
              </button>
            )}
            {allApproved && !isExecuting && currentSessionId && (
              <button
                className="plan-btn execute"
                onClick={() => executePlan(currentSessionId)}
              >
                Execute Plan
              </button>
            )}
            {isExecuting && (
              <span className="plan-executing-label">
                Executing... {completedCount}/{sections.length}
              </span>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
