"""
Skill Proposals Router

List, approve, or reject skill drafts generated by `skill_proposer`.
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Any, Dict, List, Optional
import logging

from ..services.skill_proposer import (
    approve_proposal,
    get_proposal,
    list_proposals,
    reject_proposal,
)

logger = logging.getLogger(__name__)

router = APIRouter()


class ApprovePayload(BaseModel):
    """Optional edit to the SKILL.md before it lands in `~/.springo/skills/<slug>/`."""
    skill_md: Optional[str] = None


@router.get("/skill-proposals")
async def list_skill_proposals(status: Optional[str] = None) -> Dict[str, Any]:
    """List all proposals. `status` optionally filters by `pending`/`approved`/`rejected`."""
    entries = list_proposals(status=status)
    return {
        "proposals": entries,
        "pending_count": sum(1 for e in entries if e.get("status") == "pending"),
        "total": len(entries),
    }


@router.get("/skill-proposals/{proposal_id}")
async def get_skill_proposal(proposal_id: str) -> Dict[str, Any]:
    entry = get_proposal(proposal_id)
    if not entry:
        raise HTTPException(status_code=404, detail=f"Proposal {proposal_id} not found")
    return entry


@router.post("/skill-proposals/{proposal_id}/approve")
async def approve_skill_proposal(proposal_id: str, payload: Optional[ApprovePayload] = None) -> Dict[str, Any]:
    entry = get_proposal(proposal_id)
    if not entry:
        raise HTTPException(status_code=404, detail=f"Proposal {proposal_id} not found")
    edited = payload.skill_md if payload else None
    result = approve_proposal(proposal_id, edited_skill_md=edited)
    if result is None:
        raise HTTPException(status_code=409, detail="Cannot approve — target skill directory already exists")
    return result


@router.post("/skill-proposals/{proposal_id}/reject")
async def reject_skill_proposal(proposal_id: str) -> Dict[str, Any]:
    entry = get_proposal(proposal_id)
    if not entry:
        raise HTTPException(status_code=404, detail=f"Proposal {proposal_id} not found")
    result = reject_proposal(proposal_id)
    if result is None:
        raise HTTPException(status_code=500, detail="Failed to reject proposal")
    return result
