"""
Springo API Models
"""
from .requests import (
    MessageRequest,
    MessageAutoRequest,
    ToolExecuteRequest,
    SessionCreateRequest,
    SessionUpdateRequest,
    Message,
    MessageContent,
    TextContent,
    ImageContent,
    ToolUseContent,
    ToolResultContent,
)

from .responses import (
    MessageResponse,
    ErrorResponse,
    ErrorDetail,
    ToolResult,
    ToolExecuteResponse,
    HealthResponse,
    Usage,
    ContentBlock,
    TextBlock,
    ToolUseBlock,
    SessionInfo,
    SessionListResponse,
    # SSE Events
    SSEMessageStart,
    SSEContentBlockStart,
    SSEContentBlockDelta,
    SSEContentBlockStop,
    SSEMessageDelta,
    SSEMessageStop,
    SSEError,
    SSEToolStart,
    SSEToolHeartbeat,
    SSEToolResult,
)

__all__ = [
    # Requests
    "MessageRequest",
    "MessageAutoRequest",
    "ToolExecuteRequest",
    "SessionCreateRequest",
    "SessionUpdateRequest",
    "Message",
    "MessageContent",
    "TextContent",
    "ImageContent",
    "ToolUseContent",
    "ToolResultContent",
    # Responses
    "MessageResponse",
    "ErrorResponse",
    "ErrorDetail",
    "ToolResult",
    "ToolExecuteResponse",
    "HealthResponse",
    "Usage",
    "ContentBlock",
    "TextBlock",
    "ToolUseBlock",
    "SessionInfo",
    "SessionListResponse",
    # SSE Events
    "SSEMessageStart",
    "SSEContentBlockStart",
    "SSEContentBlockDelta",
    "SSEContentBlockStop",
    "SSEMessageDelta",
    "SSEMessageStop",
    "SSEError",
    "SSEToolStart",
    "SSEToolHeartbeat",
    "SSEToolResult",
]
